{
  "hash": "4173f7951557f98a27387a9a8a9828d3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 2: Spatial Analysis and Visualization\"\nsubtitle: \"Healthcare Access and Equity in Pennsylvania\"\nauthor: \"Gab Chen\"\ndate: today\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n## Assignment Overview\n\n**Learning Objectives:**\n- Apply spatial operations to answer policy-relevant research questions\n- Integrate census demographic data with spatial analysis\n- Create publication-quality visualizations and maps\n- Work with spatial data from multiple sources\n- Communicate findings effectively for policy audiences\n\n---\n\n## Part 1: Healthcare Access for Vulnerable Populations\n\n### Research Question\n\n**Which Pennsylvania counties have the highest proportion of vulnerable populations (elderly + low-income) living far from hospitals?**\n\nYour analysis should identify counties that should be priorities for healthcare investment and policy intervention.\n\n### Required Analysis Steps\n\nComplete the following analysis, documenting each step with code and brief explanations:\n\n#### Step 1: Data Collection (5 points)\n\nLoad the required spatial data:\n- Pennsylvania county boundaries\n- Pennsylvania hospitals (from lecture data)\n- Pennsylvania census tracts\n\n**Your Task:**\n\n::: {.cell}\n\n:::\n\n\n**Questions to answer:**\n- How many hospitals are in your dataset? 223\n- How many census tracts? 3445\n- What coordinate reference system is each dataset in?\nhospitals is in WGS 84, pa_tracts is in NAD83, and pa_counties is in WGS 84 / Pseudo-Mercator.\n\n---\n\n#### Step 2: Get Demographic Data \n\nUse `tidycensus` to download tract-level demographic data for Pennsylvania.\n\n**Required variables:**\n- Total population\n- Median household income\n- Population 65 years and over (you may need to sum multiple age categories)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get demographic data from ACS\npa_demographic <- get_acs(\n  geography = \"tract\",\n  state = \"PA\",\n  year = 2022,\n  survey = \"acs5\",\n  output = \"wide\",\n  variables = c(\n    # Total population\n    totpop = \"B01003_001\",\n    \n    # Median household income\n    medinc = \"B19013_001\",\n    \n    # Age 65+ (male)\n    m65_66 = \"B01001_020\",\n    m67_69 = \"B01001_021\",\n    m70_74 = \"B01001_022\",\n    m75_79 = \"B01001_023\",\n    m80_84 = \"B01001_024\",\n    m85p   = \"B01001_025\",\n    \n    # Age 65+ (female)\n    f65_66 = \"B01001_044\",\n    f67_69 = \"B01001_045\",\n    f70_74 = \"B01001_046\",\n    f75_79 = \"B01001_047\",\n    f80_84 = \"B01001_048\",\n    f85p   = \"B01001_049\"\n  )\n)\n\n# Create total 65+ column\npa_demographic <- pa_demographic %>%\n  mutate(\n    elderlyE = \n       m65_66E + m67_69E + m70_74E + m75_79E + m80_84E + m85pE +\n      f65_66E + f67_69E + f70_74E + f75_79E + f80_84E + f85pE\n  ) \n\n# Drop unnecessary columns\npa_demographic <- pa_demographic[,-c(7:30)]\n  \n# Join to tract boundaries\ntract_with_data <- pa_tracts %>%\n  left_join(pa_demographic, by = \"GEOID\")\n\n# Answer the question\nsum(is.na(tract_with_data$medincE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 62\n```\n\n\n:::\n\n```{.r .cell-code}\n# Answer the question\nmedinc_PA_tracts = median(tract_with_data$medincE, na.rm = TRUE)\n```\n:::\n\n\n**Questions to answer:**\n- What year of ACS data are you using? 2022\n- How many tracts have missing income data? 62\n- What is the median income across all PA census tracts? 70188\n\n---\n\n#### Step 3: Define Vulnerable Populations \n\nIdentify census tracts with vulnerable populations based on TWO criteria:\n1. Low median household income (choose an appropriate threshold)\n2. Significant elderly population (choose an appropriate threshold)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter for vulnerable tracts based on your criteria\n# Add a new column pct_elderly to tract_with_data\ntract_with_data <- tract_with_data %>%\n  mutate(\n    pct_elderly = round(elderlyE / totpopE * 100, 1)\n  )\n\n# Define low-income and high elderly thresholds\nincome_cutoff <- quantile(tract_with_data$medincE, 0.35, na.rm = TRUE)\nelderly_cutoff <- quantile(tract_with_data$pct_elderly, 0.65, na.rm = TRUE)\n\n# Define vulnerable population with medinc lower than income_cutoff and pct_elderly higher than elderly_cutoff\n# Flag vulnerability\ntract_with_data <- tract_with_data %>%\n  mutate(\n    vulnerable = medincE <= income_cutoff &\n                 pct_elderly >= elderly_cutoff\n  )\n\n# Filter vulnerable tracts\nvulterable_tract <- tract_with_data %>%\n  filter(vulnerable)\n\n# Summary\ntract_with_data %>%\n  summarise(\n    total_tracts = n(),\n    vulnerable_tracts = sum(vulnerable, na.rm = TRUE),\n    pct_vulnerable = round(mean(vulnerable, na.rm = TRUE) * 100, 2) # vulnerable is logical, mean(vulnerable) equals to #TRUE / total rows\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 1 feature and 3 fields\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: -80.51989 ymin: 39.7198 xmax: -74.68952 ymax: 42.26986\nGeodetic CRS:  NAD83\n  total_tracts vulnerable_tracts pct_vulnerable                       geometry\n1         3445               360          10.56 POLYGON ((-76.2398 39.7213,...\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- What income threshold did you choose and why? 70188; Lowest 35% of median income among all PA census tracts.\n- What elderly population threshold did you choose and why? 21.4% elderly; Highest 35% of percentage of elderly among all PA census tracts.\n- How many tracts meet your vulnerability criteria? 360\n- What percentage of PA census tracts are considered vulnerable by your definition? 10.56%\n\n---\n\n#### Step 4: Calculate Distance to Hospitals \n\nFor each vulnerable tract, calculate the distance to the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Transform to appropriate projected CRS\n# NAD83 / UTM Zone 18N, PA lies almost entirely inside UTM Zone 18, units = meters\ntract_with_data <- st_transform(tract_with_data, 26918)\nhospitals <- st_transform(hospitals, 26918)\n\n# Calculate distance from each tract centroid to nearest hospital\n# Create tract centroids\ntract_centroids <- st_centroid(tract_with_data)\n\n# Find nearest hospital index\nnearest_index <- st_nearest_feature(tract_centroids, hospitals)\n\n# Compute distance (m)\nnearest_distance <- st_distance(\n  tract_centroids,\n  hospitals[nearest_index, ],\n  by_element = TRUE\n)\n\n# Convert to miles, 1 mile = 1609.34 meters\ntract_with_data$dist_to_hospital_miles <-\n  round(as.numeric(nearest_distance) / 1609.34, 2)\n\n# Answer the question\n# Average distance in mile\ntract_with_data %>%\n  filter(vulnerable) %>%\n  summarise(\n    avg_distance = round(mean(dist_to_hospital_miles, na.rm = TRUE), 2)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 1 feature and 1 field\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 35702.37 ymin: 4403397 xmax: 525519.1 ymax: 4681466\nProjected CRS: NAD83 / UTM zone 18N\n  avg_distance                       geometry\n1         5.51 MULTIPOLYGON (((79079.95 44...\n```\n\n\n:::\n\n```{.r .cell-code}\n# Maximum distance in mile\ntract_with_data %>%\n  filter(vulnerable) %>%\n  summarise(\n    max_distance = max(dist_to_hospital_miles, na.rm = TRUE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 1 feature and 1 field\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 35702.37 ymin: 4403397 xmax: 525519.1 ymax: 4681466\nProjected CRS: NAD83 / UTM zone 18N\n  max_distance                       geometry\n1         29.1 MULTIPOLYGON (((79079.95 44...\n```\n\n\n:::\n\n```{.r .cell-code}\n# Filter\ntract_with_data %>%\n  filter(vulnerable & dist_to_hospital_miles > 15) %>%\n  summarise(\n    vulnerable_over_15_miles = n()\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 1 feature and 1 field\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 40399.02 ymin: 4403397 xmax: 525519.1 ymax: 4647823\nProjected CRS: NAD83 / UTM zone 18N\n  vulnerable_over_15_miles                       geometry\n1                       21 MULTIPOLYGON (((174993.4 44...\n```\n\n\n:::\n:::\n\n\n**Requirements:**\n- Use an appropriate projected coordinate system for Pennsylvania\n- Calculate distances in miles\n- Explain why you chose your projection\n\n**Questions to answer:**\n- What is the average distance to the nearest hospital for vulnerable tracts? 5.51 miles\n- What is the maximum distance? 29.1 miles\n- How many vulnerable tracts are more than 15 miles from the nearest hospital? 21\n\n---\n\n#### Step 5: Identify Underserved Areas \n\nDefine \"underserved\" as vulnerable tracts that are more than 15 miles from the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create underserved variable\ntract_with_data <- tract_with_data %>%\n  mutate(\n    underserved = vulnerable & dist_to_hospital_miles > 15\n  )\n\n# Answer the question\n# Number of underserved tracts\ntract_with_data %>%\n  summarise(\n    underserved_tracts = sum(underserved, na.rm = TRUE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 1 feature and 1 field\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: 26826.63 ymin: 4397195 xmax: 525968.1 ymax: 4690730\nProjected CRS: NAD83 / UTM zone 18N\n  underserved_tracts                       geometry\n1                 21 POLYGON ((64095.69 4409209,...\n```\n\n\n:::\n\n```{.r .cell-code}\n# % of vulnerable tracts that is underserved\ntract_with_data %>%\n  summarise(\n    total_vulnerable = sum(vulnerable, na.rm = TRUE),\n    underserved = sum(underserved, na.rm = TRUE),\n    pct_underserved = round(\n      underserved / total_vulnerable * 100,\n      2\n    )\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 1 feature and 3 fields\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: 26826.63 ymin: 4397195 xmax: 525968.1 ymax: 4690730\nProjected CRS: NAD83 / UTM zone 18N\n  total_vulnerable underserved pct_underserved                       geometry\n1              360          21            5.83 POLYGON ((64095.69 4409209,...\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- How many tracts are underserved? 21\n- What percentage of vulnerable tracts are underserved? 5.83%\n- Does this surprise you? Why or why not? Yes. Only a very low percentage of vulnerable tracts are underserved by hospitals.This suggests that while vulnerable tracts exist, most are not geographically isolated from hospital access. Vulnerability may be driven more by socioeconomic conditions than physical distance.\n\n---\n\n#### Step 6: Aggregate to County Level\n\nUse spatial joins and aggregation to calculate county-level statistics about vulnerable populations and hospital access.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Make sure tract_with_data and pa_counties have the same CRS\npa_counties <- st_transform(pa_counties, st_crs(tract_with_data))\n# Spatial join tracts to counties\ntracts_with_county <- st_join(\n  tract_with_data,\n  pa_counties,\n  join = st_within   # best choice for tract inside county\n)\n\n# Fix COUNTY_NAM according to NAME.y\nlibrary(stringr)\n\ntracts_with_county <- tracts_with_county %>%\n  mutate(\n    COUNTY = str_extract(NAME.y, \"(?<=; ).*?(?= County)\")\n         )\n\n# Aggregate statistics by county\ncounty_summary <- tracts_with_county %>%\n  group_by(COUNTY) %>%   # replace with your county column name\n  summarise(\n    underserved_tracts = sum(underserved, na.rm = TRUE), # number of underserved tracts\n    vulnerable_tracts = sum(vulnerable, na.rm = TRUE), # number of vulnerable tracts\n    pct_vul_underserved = round(underserved_tracts / vulnerable_tracts * 100, 2), # Percentage of vulnerable tracts that are underserved\n    avg_dist_nearest_hospital = round(\n      mean(dist_to_hospital_miles[vulnerable], na.rm = TRUE),\n      2\n    ), #Average distance to nearest hospital for vulnerable tracts\n    total_vulnerable_population = sum(\n      totpopE[vulnerable],\n      na.rm = TRUE\n    ) # Total vulnerable population\n  )\n\n# Answer the questions\ntop5_pct_underserved <- county_summary %>%\n  arrange(desc(pct_vul_underserved)) %>%\n  slice_head(n = 5)\n  \n# Answer the questions\ncounty_population_far <- tracts_with_county %>%\n  group_by(COUNTY) %>%\n  summarise(\n    vulnerable_far_population = sum(\n      totpopE[underserved],\n      na.rm = TRUE\n    )\n  ) %>%\n  arrange(desc(vulnerable_far_population))\n\nslice(county_population_far, 1:5)\n\n\n# Spatial distribution of underserved counties\nlibrary(ggplot2)\nlibrary(units)\n\n# Create population density variable\ntracts_with_county <- tracts_with_county %>%\n  mutate(\n    area_sq_meters = st_area(geometry),\n    area_sq_miles = set_units(area_sq_meters, \"mi^2\"),\n    pop_density = totpopE / as.numeric(area_sq_miles)\n  )\n\n# Create ggplot\nggplot() +\n  geom_sf(data = tracts_with_county, aes(fill = pop_density), color = NA) +\n  geom_sf(\n    data = tracts_with_county %>% filter(underserved),\n    fill = \"cyan\",\n    color = \"black\",\n    size = 0.3\n  ) +\n  scale_fill_viridis_c(\n    trans = \"log\", \n    name = \"People per Sq Mile\", \n    labels = scales::comma,\n    direction = -1\n      ) +\n  theme_minimal() +\n  labs(\n    title = \"Population Density and Underserved Tracts in PA\"\n  )\n```\n\n::: {.cell-output-display}\n![](lab2_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Create ggplot\nggplot() +\n  geom_sf(data = tracts_with_county, aes(fill = medincE), color = NA) +\n  geom_sf(\n    data = tracts_with_county %>% filter(underserved),\n    fill = \"red\",\n    color = \"black\",\n    size = 0.3\n  ) +\n  scale_fill_viridis_c(\n    name = \"Median Income\", \n    labels = scales::dollar,\n    option = \"plasma\",\n    direction = -1\n      ) +\n  theme_minimal() +\n  labs(\n    title = \"Meidan Income and Underserved Tracts in PA\"\n  )\n```\n\n::: {.cell-output-display}\n![](lab2_files/figure-html/unnamed-chunk-6-2.png){width=672}\n:::\n:::\n\n\n**Required county-level statistics:**\n- Number of vulnerable tracts\n- Number of underserved tracts\n- Percentage of vulnerable tracts that are underserved\n- Average distance to nearest hospital for vulnerable tracts\n- Total vulnerable population\n\n**Questions to answer:**\n- Which 5 counties have the highest percentage of underserved vulnerable tracts? Cameron, Forest, Sullivan, Pike, and Dauphin.\n- Which counties have the most vulnerable people living far from hospitals? Bradford, Clearfield, Crawford, Hungtingdon, and Cameron.\n- Are there any patterns in where underserved counties are located? Underserved counties are spatially isolated and tend to located in rural areas with lower median income.\n\n---\n\n#### Step 7: Create Summary Table \n\nCreate a professional table showing the top 10 priority counties for healthcare investment.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create and format priority counties table\nlibrary(knitr)\n\n# Select top 10 priority counties\ntop10_priority <- tracts_with_county %>%\n  group_by(COUNTY) %>%\n  summarise(\n     # Total vulnerable tracts\n    vulnerable_tracts = sum(vulnerable, na.rm = TRUE),\n    \n    # Total underserved tracts\n    underserved_tracts = sum(underserved, na.rm = TRUE),\n    \n     # % of vulnerable tracts that are underserved\n    pct_vulnerable_underserved = round(\n      ifelse(\n        vulnerable_tracts == 0,\n        NA,\n        underserved_tracts / vulnerable_tracts * 100\n      ),\n      2\n    ),\n    \n    # Total vulnerable population\n    total_vulnerable_population = sum(\n      totpopE[vulnerable],\n      na.rm = TRUE\n    ),\n    \n    # Vulnerable population far from hospitals\n    vulnerable_far_population = sum(\n      totpopE[underserved],\n      na.rm = TRUE\n    ),\n    \n    # Avg distance for vulnerable tracts\n    avg_distance_vulnerable = round(\n      mean(dist_to_hospital_miles[vulnerable], na.rm = TRUE),\n      2\n    )\n  ) %>%\n  arrange(desc(vulnerable_far_population)) %>%\n  slice_head(n = 10)\n\n# Drop the last column, convert to a regular data frame\ntop10_priority <- st_drop_geometry(top10_priority)\n\n# kable\ntop10_priority %>%\n  # Clean format\n   mutate(\n    vulnerable_far_population = scales::comma(vulnerable_far_population),\n    total_vulnerable_population = scales::comma(total_vulnerable_population),\n    pct_vulnerable_underserved = paste0(pct_vulnerable_underserved, \"%\")\n  ) %>%\nkable(\n  col.names = c(\n    \"County\",\n    \"Vulnerable Tracts\",\n    \"Underserved Tracts\",\n    \"% of Vulnerable Tracts that Is Underserved\",\n    \"Total Vulnerable Population\",\n    \"Vulnerable Population Over 15 Miles from Hospitals\",\n    \"Average Distance from Hospitals for Vulnerable Tracts\"\n  ),\n  caption = \"Top 10 Priority Counties by Vulnerable Population Far from Hospitals\"\n)\n```\n:::\n\n\n**Requirements:**\n- Use `knitr::kable()` or similar for formatting\n- Include descriptive column names\n- Format numbers appropriately (commas for population, percentages, etc.)\n- Add an informative caption\n- Sort by priority (you decide the metric)\n\n---\n\n## Part 2: Comprehensive Visualization \n\nUsing the skills from Week 3 (Data Visualization), create publication-quality maps and charts.\n\n### Map 1: County-Level Choropleth \n\nCreate a choropleth map showing healthcare access challenges at the county level.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Transform CRS\nhospitals <- st_transform(hospitals, st_crs(tracts_with_county))\n\n# Create county-level access map\nggplot(county_summary) +\n  geom_sf(aes(fill = pct_vul_underserved), color = \"white\") +\n  \n  # Add hospital location as points\n  geom_sf(data = hospitals,\n          color = \"black\",\n          fill = \"white\",\n          shape = 21,\n          size = 2,\n          stroke = 0.5) +\n  \n  scale_fill_viridis_c(\n    option = \"plasma\",\n    direction = -1,\n    labels = scales::percent_format(scale = 1),\n    name = \"% Underserved\"\n  ) +\n  labs(\n    title = \"Percentage of Vulnerable Tracts That Are Underserved\",\n    subtitle = \"Pennsylvania Counties\",\n    caption = \"Data Source: 2022 ACS 5-Year Estimates (U.S. Census Bureau) and Hospital Locations Dataset\"\n  ) +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](lab2_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n**Requirements:**\n- Fill counties by percentage of vulnerable tracts that are underserved\n- Include hospital locations as points\n- Use an appropriate color scheme\n- Include clear title, subtitle, and caption\n- Use `theme_void()` or similar clean theme\n- Add a legend with formatted labels\n\n---\n\n### Map 2: Detailed Vulnerability Map \n\nCreate a map highlighting underserved vulnerable tracts.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a labeled variable\ntracts_with_county <- tracts_with_county %>%\n  mutate(\n    service_status = ifelse(\n      underserved,\n      \"Underserved Vulnerable Tract\",\n      \"Other Tracts\"\n    )\n  )\n\n# Create detailed tract-level map\nggplot(tracts_with_county) +\n  geom_sf(aes(fill = service_status), color = \"white\", size = 0.1) +\n  \n  scale_fill_manual(\n    values = c(\n      \"Underserved Vulnerable Tract\" = \"red\",\n      \"Other Tracts\" = \"grey85\"\n    ),\n    name = \"Tract Classification\"\n  ) +\n  \n  # Add hospital location as points\n  geom_sf(data = hospitals,\n          color = \"black\",\n          fill = \"white\",\n          shape = 21,\n          size = 2,\n          stroke = 0.5) +\n  \n  labs(\n    title = \"Underserved Vulnerable Census Tracts in Pennsylvania with Hospital Locations\",\n    subtitle = \"Low Income + High Elderly Population + >15 Miles from Nearest Hospital\",\n    caption = \"Data Source: 2022 ACS 5-Year Estimates; Hospital Locations Dataset\"\n  ) +\n  \n  theme_void()\n```\n\n::: {.cell-output-display}\n![](lab2_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n**Requirements:**\n- Show underserved vulnerable tracts in a contrasting color\n- Include county boundaries for context\n- Show hospital locations\n- Use appropriate visual hierarchy (what should stand out?)\n- Include informative title and subtitle\n\n---\n\n### Chart: Distribution Analysis\n\nCreate a visualization showing the distribution of distances to hospitals for vulnerable populations.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Histogram of Distance to Hospitals (Vulverable Tracts)\nggplot(\n  tracts_with_county %>% filter(vulnerable),\n  aes(x = dist_to_hospital_miles)\n) +\n  geom_histogram(\n    binwidth = 5,\n    fill = \"steelblue\",\n    color = \"white\"\n  ) +\n  labs(\n    title = \"Distribution of Distance to Nearest Hospital\",\n    subtitle = \"Vulnerable Census Tracts in Pennsylvania\",\n    x = \"Distance to Nearest Hospital (Miles)\",\n    y = \"Number of Vulnerable Tracts\",\n    caption = \"The distribution is right-skewed, indicating that while many vulnerable tracts are relatively close to hospitals, a subset experiences substantially longer travel distances.\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](lab2_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Bar Chart of Underserved Tracts by County\nggplot(county_summary %>% \n         arrange(desc(underserved_tracts)) %>% \n         slice_head(n = 10),\n       aes(x = reorder(COUNTY, underserved_tracts),\n           y = underserved_tracts)) +\n  geom_col(fill = \"steelblue\") +\n  coord_flip() +\n  labs(\n    title = \"Top 10 Counties by Number of Underserved Tracts\",\n    x = \"County\",\n    y = \"Number of Underserved Tracts\",\n    caption = \"A small number of counties account for a disproportionate share of underserved tracts, suggesting spatial concentration of healthcare access challenges.\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](lab2_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Scatter Plot: Distance vs Vulnerable Population\nggplot(\n  tracts_with_county %>% filter(vulnerable),\n  aes(x = dist_to_hospital_miles, y = totpopE)\n) +\n  geom_point(alpha = 0.6, color = \"steelblue\") +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"darkred\") +\n  labs(\n    title = \"Distance to Hospital vs. Vulnerable Population Size\",\n    x = \"Distance to Nearest Hospital (Miles)\",\n    y = \"Total Population in Vulnerable Tract\",\n    caption = \"While some high-population vulnerable tracts are located far from hospitals, the relationship between population size and distance appears weak, suggesting geographic isolation is not solely driven by tract size.\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](lab2_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n**Suggested chart types:**\n- Histogram or density plot of distances\n- Box plot comparing distances across regions\n- Bar chart of underserved tracts by county\n- Scatter plot of distance vs. vulnerable population size\n\n**Requirements:**\n\n- Clear axes labels with units\n- Appropriate title\n- Professional formatting\n- Brief interpretation (1-2 sentences as a caption or in text)\n\n---\n\n## Part 3: Bring Your Own Data Analysis \n\nChoose your own additional spatial dataset and conduct a supplementary analysis.\n\n### Challenge Options\n\nChoose ONE of the following challenge exercises, or propose your own research question using OpenDataPhilly data (https://opendataphilly.org/datasets/). \n\n**Note these are just loose suggestions to spark ideas - follow or make your own as the data permits and as your ideas evolve. This analysis should include bringing in your own dataset, ensuring the projection/CRS of your layers align and are appropriate for the analysis (not lat/long or geodetic coordinate systems). The analysis portion should include some combination of spatial and attribute operations to answer a relatively straightforward question**\n\n---\n\n#### Education & Youth Services\n\n**Option A: Educational Desert Analysis**\n- **Data:** Schools, Libraries, Recreation Centers, Census tracts (child population)\n- **Question:** \"Which neighborhoods lack adequate educational infrastructure for children?\"\n- **Operations:** Buffer schools/libraries (0.5 mile walking distance), identify coverage gaps, overlay with child population density\n- **Policy relevance:** School district planning, library placement, after-school program siting\n\n**Option B: School Safety Zones**\n- **Data:** Schools, Crime Incidents, Bike Network\n- **Question:** \"Are school zones safe for walking/biking, or are they crime hotspots?\"\n- **Operations:** Buffer schools (1000ft safety zone), spatial join with crime incidents, assess bike infrastructure coverage\n- **Policy relevance:** Safe Routes to School programs, crossing guard placement\n\n---\n\n#### Environmental Justice\n\n**Option C: Green Space Equity** \n- **Data:** Parks, Street Trees, Census tracts (race/income demographics)\n- **Question:** \"Do low-income and minority neighborhoods have equitable access to green space?\"\n- **Operations:** Buffer parks (10-minute walk = 0.5 mile), calculate tree canopy or park acreage per capita, compare by demographics\n- **Policy relevance:** Climate resilience, environmental justice, urban forestry investment\n---\n\n#### Public Safety & Justice\n\n**Option D: Crime & Community Resources**\n- **Data:** Crime Incidents, Recreation Centers, Libraries, Street Lights\n- **Question:** \"Are high-crime areas underserved by community resources?\"\n- **Operations:** Aggregate crime counts to census tracts or neighborhoods, count community resources per area, spatial correlation analysis\n- **Policy relevance:** Community investment, violence prevention strategies\n---\n\n#### Infrastructure & Services\n\n**Option E: Polling Place Accessibility**\n- **Data:** Polling Places, SEPTA stops, Census tracts (elderly population, disability rates)\n- **Question:** \"Are polling places accessible for elderly and disabled voters?\"\n- **Operations:** Buffer polling places and transit stops, identify vulnerable populations, find areas lacking access\n- **Policy relevance:** Voting rights, election infrastructure, ADA compliance\n\n---\n\n#### Health & Wellness\n\n**Option F: Recreation & Population Health**\n- **Data:** Recreation Centers, Playgrounds, Parks, Census tracts (demographics)\n- **Question:** \"Is lack of recreation access associated with vulnerable populations?\"\n- **Operations:** Calculate recreation facilities per capita by neighborhood, buffer facilities for walking access, overlay with demographic indicators\n- **Policy relevance:** Public health investment, recreation programming, obesity prevention\n\n---\n\n#### Emergency Services\n\n**Option G: EMS Response Coverage**\n- **Data:** Fire Stations, EMS stations, Population density, High-rise buildings\n- **Question:** \"Are population-dense areas adequately covered by emergency services?\"\n- **Operations:** Create service area buffers (5-minute drive = ~2 miles), assess population coverage, identify gaps in high-density areas\n- **Policy relevance:** Emergency preparedness, station siting decisions\n\n---\n\n#### Arts & Culture\n\n**Option H: Cultural Asset Distribution**\n- **Data:** Public Art, Museums, Historic sites/markers, Neighborhoods\n- **Question:** \"Do all neighborhoods have equitable access to cultural amenities?\"\n- **Operations:** Count cultural assets per neighborhood, normalize by population, compare distribution across demographic groups\n- **Policy relevance:** Cultural equity, tourism, quality of life, neighborhood identity\n\n---\n\n### Data Sources\n\n**OpenDataPhilly:** https://opendataphilly.org/datasets/\n- Most datasets available as GeoJSON, Shapefile, or CSV with coordinates\n- Always check the Metadata for a data dictionary of the fields.\n\n**Additional Sources:**\n- **Pennsylvania Open Data:** https://data.pa.gov/\n- **Census Bureau (via tidycensus):** Demographics, economic indicators, commute patterns\n- **TIGER/Line (via tigris):** Geographic boundaries\n\n### Recommended Starting Points\n\n**If you're feeling confident:** Choose an advanced challenge with multiple data layers. \n**If you are a beginner, choose something more manageable that helps you understand the basics**\n\n\n**If you have a different idea:** Propose your own question! Just make sure:\n- You can access the spatial data\n- You can perform at least 2 spatial operations\n\n### Your Analysis\n\n**Option C: Green Space Equity** \n- **Data:** Parks, Street Trees, Census tracts (race/income demographics)\n- **Question:** \"Do low-income and minority neighborhoods have equitable access to green space?\"\n- **Operations:** Buffer parks (10-minute walk = 0.5 mile), calculate tree canopy or park acreage per capita, compare by demographics\n- **Policy relevance:** Climate resilience, environmental justice, urban forestry investment\n\n1. **Find and load additional data**\n   - Document your data source\n   - Check and standardize the CRS\n   - Provide basic summary statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load Package\nlibrary(sf)\nlibrary(tidycensus)\nlibrary(tidyverse)\n\n#Turn off scientific notation\noptions(scipen = 999)\n\n# PPR Tree Canopy GeeoJSON\ntree <- st_read(\"E:/ArcGIS_files/Packages/Philly Data/ppr_tree_canopy_outlines_2015.geojson\")\n# PPR Properties SHP\npark <- st_read(\"E:/ArcGIS_files/Packages/Philly Data/PPR_Properties/PPR_Properties.shp\")\n\n# 2024 ACS race/income data\nvars <- c(\n  total_pop     = \"B03002_001\",  # Total population\n  white         = \"B03002_003\",  # White alone\n  black         = \"B03002_004\",  # Black or African American alone\n  hispanic      = \"B03002_012\",  # Hispanic/Latino (of any race)\n  median_income = \"B19013_001\"   # Median household income\n)\n\nphilly_data <- get_acs(\n  geography = \"tract\",\n  state = \"PA\",\n  county = \"Philadelphia\",\n  variables = vars,\n  year = 2024,\n  survey = \"acs5\",\n  output = \"wide\",\n  geometry = TRUE         # include spatial geometry if you want to map\n)\n\n# Transform to Pennsylvanis South (US Feet)\ntree <- st_transform(tree, 2272)\npark <- st_transform(park, 2272)\nphilly_data <- st_transform(philly_data, 2272)\n```\n:::\n\n\n**Questions to answer:**\n- What dataset did you choose and why? PPR Tree Canopy GeeoJSON, PPR Properties SHP, 2024 ACS race/income data\n- What is the data source and date?\n- How many features does it contain? Tree has 22407 features; Park has 504 features.\n- What CRS is it in? Did you need to transform it? Tree is in WGS 84; Park is in WGS 84 / Pseudo-Mercator.\n\n---\n\n2. **Pose a research question**\n\nDo low-income and minority neighborhoods have equitable access to green space?\n\n**Examples:**\n- \"Do vulnerable tracts have adequate public transit access to hospitals?\"\n- \"Are EMS stations appropriately located near vulnerable populations?\"\n- \"Do areas with low vehicle access have worse hospital access?\"\n\n---\n\n3. **Conduct spatial analysis**\n\nBuffer parks (10-minute walk = 0.5 mile), calculate tree canopy or park acreage per capita, compare by demographics.\n\n**Required operations (choose 2+):**\n- Buffers\n- Spatial joins\n- Spatial filtering with predicates\n- Distance calculations\n- Intersections or unions\n- Point-in-polygon aggregation\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Buffer parks 0.5 mile = 2640 ft\npark_buffer <- st_buffer(park, dist = 2640)\n# Dissolve buffer\npark_buffer <- st_union(park_buffer)\n\n# Calculate Park Access by Tract\ntract_access <- st_intersects(\n  philly_data,\n  park_buffer,\n  sparse = FALSE\n)\n# Flag Tracts with Access\nphilly_data <- philly_data %>%\n  mutate(\n    park_access = tract_access[,1]\n  )\n\n# Calculate Park Acreage per Tract\npark$area_sqft <- st_area(park)\npark$area_acres <- as.numeric(park$area_sqft) / 43560\n\n# Fix invalid park geometries\npark <- st_make_valid(park)\n# Intersect park and tracts\npark_tract <- st_intersection(park, philly_data)\n# Recalculate area\npark_tract$area_acres <- as.numeric(st_area(park_tract)) / 43560\n# Summarize by tract\npark_by_tract <- park_tract %>%\n  group_by(GEOID) %>%\n  summarise(\n    park_acres = round(sum(area_acres, na.rm = TRUE), 2)\n  )\n# Join back to tracts\nphilly_data <- philly_data %>%\n  st_join(park_by_tract, by = \"GEOID\") %>%\n  mutate(\n    park_acres = replace_na(park_acres, 0),\n    park_acres_per_capita = round(park_acres / total_popE, 2)\n  )\n\n# Calculate Tree Canopy Acreage per Tract\ntree$area_sqft <- st_area(tree)\ntree$area_acres <- as.numeric(tree$shape_area)\n# Fix invalid tree geometries\ntree <- st_make_valid(tree)\n# Intersect tree and tracts\ntree_tract <- st_intersection(tree, philly_data)\n# Recalculate area\ntree_tract$area_acres <- as.numeric(st_area(tree_tract)) / 43560\n# Summarize by tract\ntree_by_tract <- tree_tract %>%\n  group_by(GEOID.x) %>%\n  summarise(\n    tree_acres = round(sum(area_acres, na.rm = TRUE), 2)\n  )\n# Join back to tracts\nphilly_data <- philly_data %>%\n  st_join(tree_by_tract, by = \"GEOID\") %>%\n  mutate(\n    tree_acres = replace_na(tree_acres, 0)\n  )\n\n\n\n# ggplot maps\n# Load Package\nlibrary(ggplot2)\n\n# Calculate park area per 1000\n# Flag tracts with park_acres_per_1000 lower than 0.1\nphilly_data <- philly_data %>%\n  mutate(\n    park_acres_per_1000 = (park_acres / total_popE) * 1000,\n    low_park_access = park_acres_per_1000 < 0.1\n  \n  )\n\n# Calculate % canopy coverage per tract\n# Flag tracts with tree_pct lower than 0.1\nphilly_data <- philly_data %>%\n  mutate(\n    tract_sqft = as.numeric(st_area(geometry)),\n    tree_pct = (tree_acres * 43560) / tract_sqft * 100,\n    low_tree_pct = tree_pct < 0.1\n  )\n# Calculate % black\nphilly_data <- philly_data %>%\n  mutate(\n    pct_black = blackE / total_popE * 100\n  )\n\n# Map tracts with low park access and % black\nggplot(philly_data) +\n  \n  # Base: % Black\n  geom_sf(aes(fill = pct_black)) +\n  \n  # Overlay: low park access outline\n  geom_sf(\n    data = philly_data %>% filter(low_park_access),\n    fill = NA,\n    color = \"white\",\n    size = 0.5\n  ) +\n  \n  scale_fill_viridis_c(\n    option = \"plasma\",\n    name = \"% Black Population\"\n  ) +\n  \n  labs(\n    title = \"Low Park Access and Racial Composition\",\n    subtitle = \"White outlines indicate tracts with < 0.1 park acres per 1,000 residents\",\n    caption = \"Data Source: PPR Properties; 2024 ACS 5-Year Estimates\"\n  ) +\n  \n  theme_minimal() +\n  theme(\n    axis.text = element_blank(),\n    axis.title = element_blank(),\n    panel.grid = element_blank()\n  )\n```\n\n::: {.cell-output-display}\n![](lab2_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Map tracts with low park access and median income gradient\nggplot(philly_data) +\n  \n  # Base: Median income gradient\n  geom_sf(aes(fill = median_incomeE)) +\n  \n  # Overlay: low park access\n  geom_sf(\n    data = philly_data %>% filter(low_park_access),\n    fill = NA,\n    color = \"white\",\n    size = 0.5\n  ) +\n  \n  scale_fill_viridis_c(\n    option = \"magma\",\n    labels = scales::dollar,\n    direction = -1,\n    name = \"Median Income\"\n  ) +\n  \n  labs(\n    title = \"Low Park Access and Income\",\n    subtitle = \"White outlines indicate tracts with < 0.1 park acres per 1,000 residents\",\n    caption = \"Data Source: PPR Properties; 2024 ACS 5-Year Estimates\"\n  ) +\n  \n  theme_minimal() +\n  theme(\n    axis.text = element_blank(),\n    axis.title = element_blank(),\n    panel.grid = element_blank()\n  )\n```\n\n::: {.cell-output-display}\n![](lab2_files/figure-html/unnamed-chunk-14-2.png){width=672}\n:::\n:::\n\n\n**Analysis requirements:**\n- Clear code comments explaining each step\n- Appropriate CRS transformations\n- Summary statistics or counts\n- At least one map showing your findings\n- Brief interpretation of results (3-5 sentences)\n\n**Your interpretation:**\n\nA spatial comparison of low park access with racial composition and median household income reveals clear disparities across Philadelphia census tracts. Most tracts with fewer than 0.1 park acres per 1,000 residents are characterized by medium to high shares of Black residents and comparatively low median household incomes. These patterns indicate that limited access to park resources is disproportionately concentrated in predominantly Black and lower-income neighborhoods. Overall, the results suggest a strong spatial association between park access inequities, racial composition, and socioeconomic disadvantage in Philadelphia.\n\n\n## Finally - A few comments about your incorporation of feedback!\nBased on the feedback from the first assignment, I incorporated chunk options to suppress unnecessary messages, warnings, and printed output (e.g., package loading and CRS information) to improve the clarity of the document. I also paid closer attention to formatting and overall readability, ensuring that the final submission presents results in a more organized, professional, and reader-friendly manner.\n\n---\n\n## Submission Requirements\n\n**What to submit:**\n\n1. **Rendered HTML document posted to your course portfolio** with all code, outputs, maps, and text\n   - Use `embed-resources: true` in YAML so it's a single file\n   - All code should run without errors\n   - All maps and charts should display correctly\n2. Submit the correct and working links of your assignment on Canvas\n\n---\n\n",
    "supporting": [
      "lab2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}